name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.build.txt
          pip install pytest
          pip install build
          pip install twine
      - name: Test with pytest
        run: |
          pytest
      - name: Build package
        if: ${{ success() }}
        run: |
          python -m build
      - name: Publish package
        if: ${{ success() }}
        run: |
          python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
